name: nativeBayes

on:
  watch:
    type: [ started ]



jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
      - name: 'Set up Python'
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: 'Install dependencies'
        run: pip install -r requirements.txt

      - name: 'Run script'
        run: python CNCountVectorizerPlus.py

      - name: Move generated files to a folder
          # env:
        # GITHUB_TOKEN: ${{ secrets.GithubToken }}
        run: |
          mkdir -p data
          mv -n *.txt result/
          mv -n *.json result/
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add -A
          git commit -m "ci: update data (automatically)" || exit 0
          git push
